import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import postgres from 'postgres';
const exec = promisify(execFile);
test('migração faz backup, preserva votos e médias, não reabre MVP encerrado e é idempotente', {skip:!process.env.TEST_DATABASE_URL}, async t => {
  const url = new URL(process.env.TEST_DATABASE_URL!);
  assert(['127.0.0.1','localhost'].includes(url.hostname) && url.pathname.endsWith('_test'));
  const root = postgres(url.toString(), { max:1 });
  const name = `volei_migration_${Date.now()}_test`;
  await root.unsafe(`CREATE DATABASE ${name}`);
  url.pathname = '/'+name;
  const sql = postgres(url.toString(), { max:1 });
  t.after(async()=>{await sql.end(); await root.unsafe(`DROP DATABASE ${name}`); await root.end();});
  const backupDir = await mkdtemp(path.join(tmpdir(),'volei-migration-backup-'));
  const env = {...process.env,DATABASE_URL:url.toString(),BACKUP_DIR:backupDir};
  await exec(process.execPath,['node_modules/tsx/dist/cli.mjs','--eval',"import {runMigrationAndCalculations} from './src/db/services'; import {client} from './src/db/index'; runMigrationAndCalculations().finally(()=>client.end());"],{env});
  await sql`INSERT INTO players(id,name,phone,avatar_bg) VALUES ('one','One','11911111111','blue'),('two','Two','11922222222','red')`;
  await sql`INSERT INTO matches(id,date,status,team_a_name,team_a_color,team_b_name,team_b_color,created_at,finalized_at) VALUES ('old','2026-06-01','finalizada','A','blue','B','red','2026-06-01T20:00:00Z','2026-06-01T20:00:00Z'),('current','2026-07-01','finalizada','A','blue','B','red','2026-07-01T20:00:00Z','2026-07-01T20:00:00Z')`;
  await sql`INSERT INTO rating_feedbacks(id,match_id,evaluator_phone,target_player_id,rating,created_at) VALUES ('r1','old','11911111111','two',3,'2026-06-01T21:00:00Z'),('r2','current','11911111111','two',5,'2026-07-01T21:00:00Z')`;
  await sql`INSERT INTO mvp_votes(id,match_id,evaluator_phone,target_player_id,created_at) VALUES ('v1','current','11911111111','two','2026-07-01T21:00:00Z')`;
  await exec(process.execPath,['node_modules/tsx/dist/cli.mjs','src/db/migrate.ts'],{env});
  const files=await readdir(backupDir);assert.equal(files.length,1);
  const list=await exec('pg_restore',['--list',path.join(backupDir,files[0])]);assert.match(list.stdout,/TABLE DATA public rating_feedbacks/);
  assert.equal((await sql`SELECT * FROM rating_feedbacks`).length,2);
  assert.equal((await sql`SELECT avg(rating)::float8 AS mean FROM rating_feedbacks`)[0].mean,4);
  assert.equal((await sql`SELECT * FROM mvp_votes`).length,1);
  assert.equal((await sql`SELECT sex FROM players WHERE id='one'`)[0].sex,null);
  assert.equal((await sql`SELECT * FROM season_results`).length,0);
  const [match]=await sql`SELECT * FROM matches WHERE id='current'`;
  assert.equal(match.season_id,'2026-Q3');
  assert.equal(Date.parse(match.voting_closes_at),Date.parse('2026-07-02T20:00:00Z'));
  await exec(process.execPath,['node_modules/tsx/dist/cli.mjs','src/db/migrate.ts'],{env});
  assert.equal((await readdir(backupDir)).length,1);
  assert.equal((await sql`SELECT * FROM rating_feedbacks`).length,2);
});
